### ISSUE TITLE
Not an issue, a question: RMT_CLK_DIV 100 or 80?

### ISSUE THREAD

**Issue by crazyquark** [kimeckert/ESP32-RMT-server#1]
This rocks!

Just a question, looking back at rmt_nec_tx_rx - why did you modify RMT_CLK_DIV from 100 to 80?
For my remote I had to set it to 100 so it would work.

I guess that means the interval is 0.8us and not 1us?

**Comment by kimeckert** [comment]
The value of RMT_CLK_DIV is the division rate from the APB clock, normally 80MHz.  My use of a divison rate of 80 results in a RMT channel clock of 1MHz, period of 1 microsecond.  You can change RMT_CLK_DIV to 100, which will result in a channel clock frequency of 800KHz, period of 1.25 microseconds.  This gives you slightly coarser timing resolution and slightly longer maximum pulse measurement.

The reason that I changed the value from 80 to 100 is because I wanted to make the measurement in microseconds easy to measure/generate, without having to scale the RMT duration by 1.25.  You can certainly use whatever value gives you the best tradeoff of timing resolution versus maximum pulse duration.  Just make sure that you scale the durations accordingly.

**Comment by crazyquark** [comment]
Cool, thank you.
