### ISSUE TITLE
How to question: Transmit ONLY

### ISSUE THREAD

**Issue by ba58smith** [kimeckert/ESP32-RMT-server#3]
I'm trying to use an ESP32 with IR emitter / receiver as a tachometer. I want to use the RMT function to blink the LED at 38kHz, and searching for how to do that has led me to this project. Hopefully this is a quick and easy question for you. If all I want to do is blink the LED at 38kHz, it looks like the only parts of your code I need are:
```
// RMT values
#define RMT_TX_CHANNEL RMT_CHANNEL_0
#define RMT_TX_GPIO    GPIO_NUM_26
// channel clock period = 1 uS
#define RMT_CLK_DIV    80
``` 
and your `rmt_tx_ini()` function, which I would call in the setup section of my Arduino sketch.

Does that seem correct? Thanks so much - I know you're done with this project, but it's the best example I've found of what I think I want to do, so I hope you see this, and can give a quick answer.

**Comment by kimeckert** [comment]
It is not clear if you want to transmit bursts of 38kHz IR data or continuous 38kHz transmissions.  If you want continuous operation, the RMT is not appropriate.  Instead, use the LED PWM peripheral.

If you want to use the RMT in transmit mode, you need to initialize all of the registers shown in **rmt_tx_init()**.  You may need to change some of the values if you connect your IR LED differently than my example.  For example, I used 
**rmt_tx.tx_config.idle_level      = RMT_IDLE_LEVEL_LOW;**
and
**rmt_tx.tx_config.carrier_level   = RMT_CARRIER_LEVEL_HIGH;**
because my LED is ON when the output pin a high voltage (3.3V), and is OFF when the output pin is a low voltage (0V).

Transmit bursts of 38kHz IR data by constructing an array of RMT items (rmt_item32_t* items) as in
**pushItem( items, c, false, -1\*val.num );**
Then have the RMT use this array to transmit the bursts by
**rmt_write_items(RMT_TX_CHANNEL, items, size, true);**
You can find examples of this in 
**send_duration( char\* buf, u16_t start, u16_t end )**

If you always send the same burst, you can construct the array once and call rmt_write_items() multiple times with the same array.

**Comment by ba58smith** [comment]
Kim, I want a continuous flashing IR LED, flashing at 38kHz. So, thanks for the pointer to the LED PWM peripheral! (I'm hoping that if I flash the LED continually at 38kHz, and use an IR receiver that recognizes only 38kHz flashes, I'll be able to construct a tachometer that will work even in the presence of other visible light. The spinning part of the engine will have 1" long strips of reflective tape, and I will use an interrupt to count the number of times the IR receiver "sees" the light reflecting off the tape strips. I know that the IR receiver needs to NOT have firmware that is expecting "bursts" of 38kHz pulses, but rather, one that simply outputs HIGH when the tape is "seen", and LOW when it's not - or vice versa.)

**Comment by kimeckert** [comment]
That sounds good.  I have not used the LED PWM, but the API looks understandable:
[https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/ledc.html](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/ledc.html)

For your application, I would suggest a matched IR emitter/receiver pair that is designed for that purpose.  Some I have seen are from Adafruit:
Reflective pair [https://www.adafruit.com/product/3930](https://www.adafruit.com/product/3930)
Separate send/receive: [https://www.adafruit.com/product/2167](https://www.adafruit.com/product/2167)
Same, assembled in a bracket with a slot between them: [https://www.adafruit.com/product/3986](https://www.adafruit.com/product/3986)

Note that an IR beam modulated at 38kHz will give you increased immunity to ambient light and will increase the distance that you can use between the transmitter and receiver, when compared to an unmodulated IR beam.  At short distances and little ambient light, you should be able to use an unmodulated beam.  The downside of using a modulated IR beam is that the detector response will be longer than for an unmodulated beam.  That may not be a problem for your application.

**Comment by ba58smith** [comment]
Thank you for that great info! I really appreciate it.
